### ISSUE TITLE
API allows anonymous user to create an org

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#66] opened 2015-01-12 15:35 UTC
currently the web UI's view is blocking this, but should block this at the API level as well.

**Comment by MisterNando** [comment] 2015-01-24 22:48
Estimates:

Original - N/A
Updated - 1h

**Comment by MisterNando** [comment] 2015-02-22 20:50
@pkshiu , @paynejd , there is no notion of an "anonymous" user at the API level.  If you have a token, then you should be able to create an org.  Is this correct, Jon?

**Comment by paynejd** [comment] 2015-02-27 04:08
Agreed that there is no notion of "anonymous" at the API level -- this is just another token. But, the user associated with this token should be restricted from editing any content or from viewing any private content. Seems like the latter is there by default -- is it possible to the former?

**Comment by MisterNando** [comment] 2015-02-28 00:36
Only a superuser is allowed to create another user, but any user can create an org.  Should we make it so that only a superuser can create an org as well?

**Comment by paynejd** [comment] 2015-03-03 17:59
Let's delay this ticket. It has been handled on the Web app side.

--
Jonathan Payne, MS
615.579.5413
*LinkedIn:* www.linkedin.com/in/jonathandavidpayne
*Skype:* jonathandavidpayne

**Comment by paynejd** [comment] 2015-03-10 05:08
While this is not the preferred behavior of the "anonymous" user, turns out this is not a bug -- the "anonymous" user is just behaving like any user at the API level, which means they can create resources. For the time being, permissions for this user will be handled at the Web Application level.

Closing and shifting into #100

**Closed by paynejd** 2015-03-10 05:08 UTC
Labels: bug, medium-priority
